config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get '/main', to: 'dashboards#main', as: :main
  resources :dashboards

  resources :opportunities do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :cases do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :marketings do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :accounts do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end
    get '/delete_attachment/:id',
    to: 'accounts#delete_attachment', as: :delete_attachment
    resources :timelines
    resources :notes
    resources :opportunities
  end

  get '/tasks', to: 'tasks#index'
  get '/calls', to: 'calls#index'
  get '/contacts', to: 'contacts#index'
  get '/events', to: 'events#index'
  get '/notes', to: 'notes#index'
  get '/notifications', to: 'notifications#index'

  resources :users
  resources :contacts do
    member do
      delete '/destroy_relationship/:relationship_id',
      to: 'contacts#destroy_relationship', as: :destroy_relationship
    end
  end

  get '/notifications/:id', to: 'notifications#update_read_status', as: :update_read_status
  get '/sales_index', to: 'dashboards#sales_index', as: :sales_index
  get '/marketing_index', to: 'dashboards#marketing_index', as: :marketing_index

  root 'dashboards#main'

  get '/search', to: 'search#search'
  get "*path" => redirect("/")
end

app/models/note.rb
class Note < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :user
  belongs_to :info, polymorphic: true

  validates :title, presence: true

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_subject
  before_action :find_note, only: [:edit, :update, :destroy]

  def index
    if params[:type]
      @notes = Note.includes(:user, :info).where(
      info_type: params[:type]).order('created_at').page(params[:page]).per(10)
    else
      @notes = Note.includes(:user, :info).order('created_at').page(params[:page]).per(10)
    end
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def create
    @note = @subject.notes.build(params_note)
    @note.user_id = current_user.id

    respond_to do |format|
      if @note.save
        @notetimeline = @subject.timelines.create!(
        action: "#{current_user.name} created note <strong>#{@note.title.truncate(50)}</strong>",
        anchor: "relatedNotes",
        user_id: current_user.id
        )
        format.js { flash.now[:success] = "Note log added!" }
      else
        format.js { flash.now[:danger] = "Failed to add note log!" }
      end
    end

  end

  def edit

  end

  def update
    @old_title = @note.title
    @old_description = @note.description

      if @note.update(params_note)
        # timeline
        if @note.title_previously_changed?
          timeline_note("title", @old_title, @note.title)
        elsif @note.description_previously_changed?
          timeline_note("description", @old_description, @note.description)
        end


        flash[:success] = "Note entry created!"
        if params[:controller] == "accounts" || params[:account_id]
          redirect_to account_path(@subject, anchor: "relatedNotes")
        elsif params[:controller] == "opportunities" || params[:opportunity_id]
          redirect_to opportunity_path(@subject, anchor: "relatedNotes")
        end
      else
        flash[:danger] = "Failed to create note entry!"
        render 'edit'
      end
  end

  def destroy
    @note.destroy
    @notetimeline = @subject.timelines.create!(
    action: "#{current_user.name} deleted note <strong>#{@note.title.truncate(50)}</strong>",
    anchor: "relatedNotes",
    user_id: current_user.id
    )
    respond_to do |format|
      format.js { flash.now[:success] = "Note log deleted!" }
    end

    # AJAX
    @notes = Note.includes(:user, :info).order('created_at').page(params[:page]).per(10)
  end

  private

  def timeline_note(param, old, latest)
    @notetimeline = @subject.timelines.create!(
    action: "#{current_user.name} updated note <strong>#{param}</strong> from
    <strong>#{old}</strong> to <strong>#{latest}</strong>",
    anchor: "relatedNotes",
    user_id: current_user.id
    )
  end

  def params_note
    params.require(:note).permit(:title, :description)
  end

  def find_subject
    @subject = Account.find(params[:account_id]) if params[:account_id]
    @subject = Opportunity.find(params[:opportunity_id]) if params[:opportunity_id]
    @subject = Marketing.find(params[:marketing_id]) if params[:marketing_id]
    @subject = Case.find(params[:case_id]) if params[:case_id]
  end

  def find_note
    find_subject
    @note = @subject.notes.find(params[:id])
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <h3>Edit Note</h3>
        <hr>
        <strong>Belongs to</strong><br>

        <% if @note.info_type == "Opportunity" %>
          <small><%= @note.info_type %></small><br>
          <%= link_to @note.info.name, opportunity_path(@note.info) %><br>
        <% elsif @note.info_type == "Account" %>
          <small><%= @note.info_type %></small><br>
          <%= link_to @note.info.name, account_path(@note.info) %><br>
        <% end %>

        <br>
        <%= simple_form_for [@subject, @note] do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>

        <% if params[:account_id] %>
        <%= link_to 'Back',
        account_path(@subject, anchor: "relatedNotes-#{@note.id}"),
        class: "btn btn-default" %>
        <% elsif params[:opportunity_id] %>
        <%= link_to 'Back',
        opportunity_path(@subject, anchor: "relatedNotes-#{@note.id}"),
        class: "btn btn-default" %>
        <% end %>

        <%= f.button :submit, class: "btn btn-success" %>

        <% end %>
    </div>
    <div class="col-lg-3"></div>
</div>

app/views/notes/_note.html.erb
<h4>Notes</h4>
<hr>
<div id="notice-note"></div>
<% if @subject.notes.blank? %>
No notes found.
<% else %>

<% @subject.notes.includes(:info, :user).order('created_at DESC').page(params[:note_page]).per(10).each do |note| %>
<div class="col-lg-6 panel panel-body" id="relatedNotes-<%= note.id %>">
    <div class="dropdown pull-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="caret"></i>
        </a>
        <ul class="dropdown-menu">
            <li><%= link_to 'Show', '#', data: {toggle: "modal", target: "#noteInfo-#{note.id}"}%></li>
            <li>
              <% if params[:controller] == "opportunities" || params[:opportunity_id] %>
              <%= link_to 'Edit', edit_opportunity_note_path(@subject, note) %>
              <% elsif params[:controller] == "accounts" || params[:account_id] %>
              <%= link_to 'Edit', edit_account_note_path(@subject, note) %>
              <% end %>
            </li>
            <% if params[:controller] == "opportunities" || params[:opportunity_id] %>
            <li><%= link_to 'Delete',
            opportunity_note_path(@subject, note), method: :delete, remote: true,
            data: {confirm: "Are you sure?"} %></li>
            <% elsif params[:controller] == "accounts" || params[:account_id] %>
            <li><%= link_to 'Delete',
        account_note_path(@subject, note), method: :delete, remote: true,
        data: {confirm: "Are you sure?"} %></li>
            <% end %>
        </ul>
    </div>

    <h5>
        <%= link_to note.title.truncate(40), '#',
          data: {toggle: "modal", target: "#noteInfo-#{note.id}"} %>
          <br>
        <small>
            <%= time_ago_in_words(note.created_at) %>
            ago
        </small>
    </h5>
    <%= note.description.truncate(100) %>
</div>
<%= render 'notes/note_info', note: note %>
<% end %>
<div class="row">
<div class="col-lg-12 text-center">
  <%= paginate @subject.notes.includes(:info, :user).page(params[:note_page]).per(10), param_name: :note_page, remote: true %>
</div>
</div>
<% end %>

app/views/notes/_note_info.html.erb
<!-- Modal -->
<div id="noteInfo-<%= note.id %>" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">
                    Note
                </h4>
            </div>
            <div class="modal-body">

              <h5>
                  <small>Title</small>
              </h5>
              <%= note.title %>
              <br><br>
              <h5>
                  <small>Description</small>
              </h5>
              <%= simple_format h(note.description) %>
              <hr>

                <div class="row">
                    <div class="col-lg-6">
                        <h5>
                            <small>Belongs to</small>
                        </h5>
                        <% if note.info_type == "Opportunity" %>

                        <small><%= note.info_type %></small><br>
                        <%= link_to note.info.name,
                        opportunity_path(note.info, anchor: "relatedNotes-noteInfo-#{note.id}") %>

                        <% elsif note.info_type == "Account" %>

                        <small><%= note.info_type %></small><br>
                        <%= link_to note.info.name,
                        account_path(note.info, anchor: "relatedNotes-noteInfo-#{note.id}") %>

                        <% end %>
                        <br><br>
                    </div>
                    <div class="col-lg-6">
                      <h5>
                          <small>Note created by</small>
                      </h5>
                      <%= link_to note.user.name, user_path(note.user) %>
                    </div>
                </div>
                <br>
                <div class="row">
                  <div class="col-lg-6">
                    <h5>
                        <small>Created at</small>
                    </h5>
                    <%= note.created_at.strftime('%d %b %Y at %H:%M:%S') %>
                    <br><br>
                  </div>
                  <div class="col-lg-6">
                    <h5>
                        <small>Last updated at</small>
                    </h5>
                    <%= note.updated_at.strftime('%d %b %Y at %H:%M:%S') %>
                  </div>
                </div>

            </div>
            <div class="modal-footer">
                <%= link_to 'Close', '#', class: "btn btn-default", data: {dismiss: "modal"}%>
            </div>
        </div>
    </div>
</div>

app/views/notes/_note_list.html.erb
<div id="notice-note">
    <%= render 'layouts/message' %>
</div>

<hr>

<div class="row">
    <div class="col-lg-1 col-xs-1 text-center">
        <strong>ID</strong>
    </div>
    <div class="col-lg-2 col-xs-10">
        <strong>Title</strong>
        <br><br>
    </div>
    <div class="col-lg-2 col-xs-6">
        <strong>Description</strong>
    </div>
    <div class="col-lg-2 col-xs-6">
        <strong>Belongs to</strong>
        <div class="dropdown">
            <%= link_to '#',data: {toggle: 'dropdown'}, class: 'dropdown-toggle' do %>
            Show only
            <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
                <li><%= link_to 'Account', "?type=Account" %></li>
                <li><%= link_to 'Opportunity', "?type=Opportunity" %></li>
                <li><%= link_to 'Case', " ?type=Case" %></li>
                <li><%= link_to 'Marketing', " ?type=Marketing" %></li>
                <li><%= link_to 'All', notes_path %></li>
            </ul>
        </div>
        <br><br>
    </div>
    <div class="col-lg-2 col-xs-6">
        <strong>Created At DateTime</strong>
    </div>
    <div class="col-lg-2 col-xs-2 text-center">
        <strong>Action</strong>
    </div>
</div>

<% if @notes.blank? %>

<hr>
<div class="text-center">
    No
    <%= params[:type] %>
    notes found.<br><br>
    Create note through subject.
</div>

<% else %>

<% @notes.each do |note| %>
<hr>
<div class="row">
    <div class="col-lg-1 col-xs-1 text-center">
        <span class="badge"><%= note.id %></span>
    </div>
    <div class="col-lg-2 col-xs-10">
        <%= link_to note.title, '#', data: {toggle: "modal", target: "#noteInfo-#{note.id}"} %>
        <br><br>
    </div>
    <div class="col-lg-2 col-xs-6">
      <% if note.description.blank? %>
      <span style="color: red;">Not specified</span>
      <% else %>
        <%= note.description.truncate(50) %>
      <% end %>
    </div>
    <div class="col-lg-2 col-xs-6">
        <small><%= note.info_type %></small><br>
        <%= link_to note.info.name, polymorphic_path(note.info) %>
        <br><br>
    </div>
    <div class="col-lg-2 col-xs-6"><%= note.created_at.strftime('%d %b %Y at %H:%M:%S') %></div>
    <div class="col-lg-2 col-xs-2 text-center">
        <a href="#" class="dropdown-toggle btn btn-default" data-toggle="dropdown">
            <i class="caret"></i>
        </a>
        <ul class="dropdown-menu">
            <li><%= link_to 'Show', polymorphic_path(note.info, anchor: "relatedNotes-noteInfo-#{note.id}") %></li>
            <li><%= link_to 'Edit', edit_polymorphic_path([note.info, note]) %></li>
            <li><%= link_to 'Delete', polymorphic_path([note.info, note]),
            method: :delete, data: {confirm: "Are you sure?"}, remote: true %></li>
        </ul>
    </div>
</div>

<%= render 'notes/note_info', note: note %>
<% end %>
<br>
<div class="text-center">
    <%= paginate @notes %>
</div>
<% end %>

app/views/notes/_related_notes.html.erb
<div class="tab-pane fade in" id="relatedNotes">
    <h4>Related Notes</h4>
    <div class="panel panel-default panel-body">
        <%= simple_form_for [@subject, @note, Note.new], remote: true do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.button :submit %>
        <% end %>
    </div>
    <br>

    <div class="note">
      <%= render 'notes/note' %>
    </div>
</div>

app/views/notes/create.js.erb
$('.note').html("<%= j (render 'notes/note') %>");
$('#notice-note').html("<%= j (render 'layouts/message') %>").delay(1600).fadeOut();

$('.timelines').html("<%= j (render 'timelines/timelines_index') %>");

$('.modal').modal('hide');
$('#crm-menu').html("<%= j (render 'layouts/menu') %>");

$('#note_title').val('');
$('#note_description').val('');

app/views/notes/destroy.js.erb
$('.note').html("<%= j (render 'notes/note') %>");
$('.task-list').html("<%= j (render 'notes/note_list') %>");
$('.timelines').html("<%= j (render 'timelines/timelines_index') %>");
$('#notice-note').html("<%= j (render 'layouts/message') %>").delay(1600).fadeOut();
$('#crm-menu').html("<%= j (render 'layouts/menu') %>");

app/views/notes/edit.html.erb
<%= render 'form' %>

app/views/notes/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="media">
            <div class="media-left">
                <div style="padding-top: 20px;"></div>
                <%= letter_avatar_tag('Notes', 50, class: "media-object") %>
            </div>
            <div class="media-body">
                <h3>Notes<br>
                    <small>
                      <%= params[:type] ? params[:type] : 'All' %> Notes and Reminders
                    </small>
                </h3>
            </div>
        </div>
    </div>
</div>

<div class="task-list">
    <%= render 'notes/note_list' %>
</div>

<%= javascript_tag defer: 'defer' do %>
var locHash = window.location.hash.split('-')
var id = '#' + locHash[1] + '-' + locHash[2];
$(id).modal('show');
<% end %>

app/views/notes/index.js.erb
$('.timelines').html("<%= j (render 'timelines/timelines_index') %>");

app/views/notes/update.js.erb
$('.modal').modal('hide');

$('.note').html("<%= j (render 'notes/note') %>");
$('.timelines').html("<%= j (render 'timelines/timelines_index') %>");
$('#notice-note').html("<%= j (render 'layouts/message') %>").delay(1600).fadeOut();
$('#crm-menu').html("<%= j (render 'layouts/menu') %>");