config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get '/main', to: 'dashboards#main', as: :main
  resources :dashboards

  resources :opportunities do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :cases do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :marketings do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :accounts do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end
    get '/delete_attachment/:id',
    to: 'accounts#delete_attachment', as: :delete_attachment
    resources :timelines
    resources :notes
    resources :opportunities
  end

  get '/tasks', to: 'tasks#index'
  get '/calls', to: 'calls#index'
  get '/contacts', to: 'contacts#index'
  get '/events', to: 'events#index'
  get '/notes', to: 'notes#index'
  get '/notifications', to: 'notifications#index'

  resources :users
  resources :contacts do
    member do
      delete '/destroy_relationship/:relationship_id',
      to: 'contacts#destroy_relationship', as: :destroy_relationship
    end
  end

  get '/notifications/:id', to: 'notifications#update_read_status', as: :update_read_status
  get '/sales_index', to: 'dashboards#sales_index', as: :sales_index
  get '/marketing_index', to: 'dashboards#marketing_index', as: :marketing_index

  root 'dashboards#main'

  get '/search', to: 'search#search'
  get "*path" => redirect("/")
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:term].nil?
      @results = []
    else
      @results = Elasticsearch::Model.search(params[:term],
      [
        Account,
        Contact,
        Opportunity,
        Task,
        Call,
        Event,
        User
        ]).page(params[:page]).per(10)
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<div class="container">
    <h3>Search Results</h3>
    <hr>
    <% if @results.blank? %>
    No results match
<% else %>

    <% @results.each do |result| %>

    <div class="row">
      <div class="col-lg-6">
        <% if result._index == "accounts" %>
        <h4 style="margin-bottom: 0px;"><%= link_to result.name, account_path(result.id) %><br>
          <small>Account</small>
        </h4>
        <%= result.account_type %>,
        <%= result.description %>,
        <%= result.email %>,
        <%= result.phone %>
        <br>
        <% elsif result._index == "contacts" %>
        <% page_num = (result.id.to_i / 10) + 1 %>
        <h4 style="margin-bottom: 0px;"><%= link_to result.name, contacts_path(page: page_num, anchor: "contactInfo-#{result.id}") %><br>
          <small>Contact</small>
        </h4>
        <%= result.title %>,
        <%= result.department %>,
        <%= result.email %>,
        <%= result.phone %>
        <br>

        <% elsif result._index == "opportunities" %>
        <h4 style="margin-bottom: 0px;"><%= link_to result.name, opportunity_path(result.id) %><br>
          <small>Opportunity</small>
        </h4>
        <%= result.description.truncate(200) %>,
        Status: <%= result.status %>,
        Amount: RM<%= result.amount %>
        <br>

        <% elsif result._index == "tasks" %>
        <h4 style="margin-bottom: 0px;">
          <%= link_to result.description.truncate(50), opportunity_path(
          result.opportunity_id, anchor: "task-taskInfo-#{result.id}") %><br>
          <small>Task</small>
        </h4>

        <% elsif result._index == "calls" %>
        <h4 style="margin-bottom: 0px;">
          <%= link_to result.description.truncate(50), opportunity_path(
          result.opportunity_id, anchor: "call-callInfo-#{result.id}") %><br>
          <small>Call</small>
        </h4>

        <% elsif result._index == "events" %>
        <h4 style="margin-bottom: 0px;">
          <%= link_to result.description.truncate(50), opportunity_path(
          result.opportunity_id, anchor: "event-eventInfo-#{result.id}") %><br>
          <small>Event</small>
        </h4>

        <% elsif result._index == "stages" %>
        <h4 style="margin-bottom: 0px;">
          <%= link_to result.name, opportunity_path(result.opportunity_id) %><br>
          <small>Stage</small>
        </h4>
        <% if result.status == "Waiting" %>
        <%= result.status %>
        for previous stage
        <% else %>
        <%= result.status %>
        <% end %>
        <br>

        <% elsif result._index == "users" %>
        <h4 style="margin-bottom: 0px;">
          <%= link_to result.name, user_path(result.id) %><br>
          <small>User</small>
        </h4>
        <%= result.email %>
        <%= result.phone %>
        <%= result.title %>
        <%= result.department %>
        <% end %>
      </div>
    </div>
    <br>
    <% end %>

    <div class="text-center">
    <%= paginate @results %>
    </div>

    <% end %>
</div>