config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get '/main', to: 'dashboards#main', as: :main
  resources :dashboards

  resources :opportunities do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :cases do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :marketings do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :accounts do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end
    get '/delete_attachment/:id',
    to: 'accounts#delete_attachment', as: :delete_attachment
    resources :timelines
    resources :notes
    resources :opportunities
  end

  get '/tasks', to: 'tasks#index'
  get '/calls', to: 'calls#index'
  get '/contacts', to: 'contacts#index'
  get '/events', to: 'events#index'
  get '/notes', to: 'notes#index'
  get '/notifications', to: 'notifications#index'

  resources :users
  resources :contacts do
    member do
      delete '/destroy_relationship/:relationship_id',
      to: 'contacts#destroy_relationship', as: :destroy_relationship
    end
  end

  get '/notifications/:id', to: 'notifications#update_read_status', as: :update_read_status
  get '/sales_index', to: 'dashboards#sales_index', as: :sales_index
  get '/marketing_index', to: 'dashboards#marketing_index', as: :marketing_index

  root 'dashboards#main'

  get '/search', to: 'search#search'
  get "*path" => redirect("/")
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :attchdoc, polymorphic: true

  has_attached_file :doc,
                    styles: { thumb: "200x250#" },
                    default_url: "/images/:style/missing.png",
                    dependent: :destroy

  validates_attachment_content_type :doc,
  content_type:
  [
    "application/pdf",
    "application/vnd.ms-excel",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "text/plain",
    /\Aimage\/.*\z/ # accept all type of images
  ]
end

app/views/documents/_doc.html.erb
<div id="notice-doc"></div>
<div class="row">
<% if @subject.documents.blank? %>
<div class="col-lg-12">
    <p>No documents found.</p>
</div>
<% else %>

<% @subject.documents.each_with_index do |document, index| %>
<% if (index+1) % 4 == 0 %>
<div class="row">
    <% end %>
    <div class="col-lg-3 text-center">
        <br>
        <a href="#" data-toggle="modal" data-target="#modal-agreement-<%= document.id %>">
            <%= image_tag(document.doc.url(:thumb), class: "img-responsive img-center") %>
        </a>
        <% if params[:controller] == "opportunities" %>
        <%= link_to opportunity_delete_attachment_path(@subject, document), remote: true do %>
          <i class="fa fa-times"></i>
        <% end %>
        <% elsif params[:controller] == "accounts" %>
        <%= link_to account_delete_attachment_path(@subject, document), remote: true do %>
          <i class="fa fa-times"></i>
        <% end %>
        <% end %>
    </div>

    <% if (index+1) % 4 == 0 %>
</div>
<% end %>

<div class="modal fade" id="modal-agreement-<%= document.id %>">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <object data="<%= document.doc.url%>" width="100%" height="500" style="height: 85vh;">No Support</object>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<% end %>

<% end %>
</div>

app/views/documents/_related_docs.html.erb
<div class="tab-pane fade in" id="relatedDocs">
    <h4>Related Documents</h4>
    <% @subject = Account.find(params[:id]) if params[:controller] == "accounts" %>
    <% @subject = Opportunity.find(params[:id]) if params[:controller] == "opportunities" %>

    <div class="panel panel-default panel-body">
        <%= simple_form_for @subject, html: {multipart: true}, remote: true do |f| %>
        <!-- dummy for the sake of saving the file -->
        <%= f.input :dummy, as: :hidden %>

        <%= f.label "Upload Documents" %>
        <%= file_field_tag "docs[]",type: :file, multiple: true %>
        <%= f.hint "Can upload multiple files." %>
        <%= f.hint "Support pdf and all type of images file" %>
        <%= f.button :submit, "Submit Documents" %>
        <% end %>
    </div>

    <div id="doc">
        <%= render 'documents/doc' %>
    </div>

</div>