config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get '/main', to: 'dashboards#main', as: :main
  resources :dashboards

  resources :opportunities do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :cases do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :marketings do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end

    get '/delete_attachment/:id',
    to: 'opportunities#delete_attachment', as: :delete_attachment

    resources :timelines
    resources :stages do
      member do
        get '/update_status', to: 'stages#update_stage_status'
      end
    end
    resources :tasks do
      member do
        get '/update_task_status', to: 'tasks#update_task_status'
      end
    end
    resources :calls
    resources :events do
      member do
        get '/update_event_status', to: 'events#update_event_status'
      end
    end

    resources :notes
  end

  resources :accounts do
    resources :contacts do
      member do
        delete '/destroy_relationship/:relationship_id',
        to: 'contacts#destroy_relationship', as: :destroy_relationship
      end
    end
    get '/delete_attachment/:id',
    to: 'accounts#delete_attachment', as: :delete_attachment
    resources :timelines
    resources :notes
    resources :opportunities
  end

  get '/tasks', to: 'tasks#index'
  get '/calls', to: 'calls#index'
  get '/contacts', to: 'contacts#index'
  get '/events', to: 'events#index'
  get '/notes', to: 'notes#index'
  get '/notifications', to: 'notifications#index'

  resources :users
  resources :contacts do
    member do
      delete '/destroy_relationship/:relationship_id',
      to: 'contacts#destroy_relationship', as: :destroy_relationship
    end
  end

  get '/notifications/:id', to: 'notifications#update_read_status', as: :update_read_status
  get '/sales_index', to: 'dashboards#sales_index', as: :sales_index
  get '/marketing_index', to: 'dashboards#marketing_index', as: :marketing_index

  root 'dashboards#main'

  get '/search', to: 'search#search'
  get "*path" => redirect("/")
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :activity, polymorphic: true
  belongs_to :user

  has_many :notifications, dependent: :destroy
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :find_subject, only: [:show, :destroy]

  def show

  end

  def destroy
    @timeline = @subject.timelines.find(params[:id])
    @timeline.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def find_subject
    @subject = Opportunity.find(params[:opportunity_id]) if params[:opportunity_id]
    @subject = Account.find(params[:account_id]) if params[:account_id]

  rescue ActiveRecord::RecordNotFound
    flash[:danger] = "Can't find records!"
    redirect_to root_path
  end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_index.html.erb
<h4>Timeline &middot History</h4>

<% if @opportunity.timelines.blank? %>
<p>Every changes regarding opportunities will be recorded here.</p>
<% else %>

<% @opportunity.timelines.order('created_at DESC').each do |timeline| %>
<div class="panel panel-default panel-body">
    <div class="media">
        <div class="media-left" style="padding-top: 6px;">
            <%= image_tag('http://placehold.it/25x25', class: "media-object")%>
        </div>
        <div class="media-body">
            <small>
                <%= link_to timeline.user.name, user_path(timeline.user.id) %>
                <%= timeline.action %>
                <strong><%= timeline.nactivity %></strong>
                <div class="pull-right">
                <%= link_to opportunity_timeline_path(@opportunity, timeline),
                method: :delete do %>
                <i class="fa fa-times"></i>
                <% end %>
              </div>
            </small>
            <h5 style="margin-top: -2px;">
                <small>
                    <%= timeline.created_at.strftime('%d %b %Y') %>
                    &middot
                    <%= time_ago_in_words(timeline.created_at) %>
                    ago
                </small>

                <h5>

            </div>
            </div>
        </div>
        <% end %>
<% end %>

app/views/timelines/_timelines_index.html.erb
<h4>Timeline &middot History</h4>

<% op = @subject.timelines.order('created_at DESC').includes(:user, :activity).page(params[:page]).per(5) %>

<% if op.blank? %>
<p>Every changes will be recorded here.</p>
<% else %>

<% tldate_current = "" %>
<% tldate_previous = "" %>

<% op.each do |timeline| %>

<% tldate_current = timeline.created_at.strftime('%B %Y') %>
<% if tldate_current != tldate_previous %>
<hr>
<div class="text-center">
<h3><small><%= tldate_current %></small></h3>
</div>
<% end %>

<div class="panel panel-default panel-body">
    <div class="media">
        <div class="media-left" style="padding-top: 6px;">
            <% if timeline.user.avatar.blank? %>
            <%= letter_avatar_tag(timeline.user.name, 25, class: "media-object")%>
        <% else %>
            <%= image_tag(timeline.user.avatar.url(:small), class: "media-object")%>
            <% end %>
        </div>
        <div class="media-body">
            <small>
                <%= timeline.action.html_safe %>
            </small>
            <h5 style="margin-top: -2px;">
                <small>
                    <%= timeline.created_at.strftime('%d %b %Y') %>
                    &middot
                    <%= time_ago_in_words(timeline.created_at) %>
                    ago
                </small>
                <h5></div>
            </div>
        </div>
        <% tldate_previous = tldate_current %>
        <% end %>
        <div class="text-center" id="paginator">
            <%= page_entries_info op %><br>
            <%= paginate op, remote: true %>
        </div>
        <% end %>

app/views/timelines/destroy.js.erb
$('.timelines').html("<%= j (render 'timelines/timelines_index') %>");